config/routes.rb
Rails.application.routes.draw do
  resources :comments

  mount RailsAdmin::Engine => '/admins/moderate', as: 'rails_admin'
  devise_for :admins
  resources :adverts do
    collection do
      get 'active'
      get 'inactive'
      get 'job_hunt'
      get 'buy'
      get 'sell'
      get 'hire'
      get 'exchange'
    end
  end
  resources :admins 
  get '/' => 'adverts#index'
  root to: 'adverts#index'

end

app/models/admin.rb
class Admin < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  has_many :adverts, dependent: :destroy

end

app/models/advert.rb
class Advert < ActiveRecord::Base
  scope :active, -> {where active: true }
  scope :inactive, -> {where active: false }
  scope :job_hunt, -> {where job_hunt: true }
  scope :buy, -> {where buy: true }
  scope :sell, -> {where sell: true }
  scope :hire, -> {where hire: true }
  scope :exchange, -> {where exchange: true }
  validates :email, presence: true
  validates :title, :name, :surname, :address, :mobile, presence: true
  validates :description , length: { minimum: 10 }
  validates :email, :email => true
  geocoded_by :address   # can also be an IP address
  after_validation :geocode          # auto-fetch coordinates
  has_attached_file :image, :styles => { :medium => "700x700>", :thumb => "100x100>" }, :default_url => "http://icons.iconarchive.com/icons/oxygen-icons.org/oxygen/96/Status-image-missing-icon.png"
  validates_attachment_content_type :image, :content_type => /\Aimage\/.*\Z/
  has_attached_file :image1, :styles => { :medium => "700x700>", :thumb => "100x100>" }, :default_url => "http://icons.iconarchive.com/icons/oxygen-icons.org/oxygen/96/Status-image-missing-icon.png"
  validates_attachment_content_type :image1, :content_type => /\Aimage\/.*\Z/
  has_attached_file :image2, :styles => { :medium => "700x700>", :thumb => "100x100>" }, :default_url => "http://icons.iconarchive.com/icons/oxygen-icons.org/oxygen/96/Status-image-missing-icon.png"
  validates_attachment_content_type :image2, :content_type => /\Aimage\/.*\Z/
  has_attached_file :image3, :styles => { :medium => "700x700>", :thumb => "100x100>" }, :default_url => "http://icons.iconarchive.com/icons/oxygen-icons.org/oxygen/96/Status-image-missing-icon.png"
  validates_attachment_content_type :image3, :content_type => /\Aimage\/.*\Z/
  belongs_to :admin
  has_many :comments, dependent: :destroy
  accepts_nested_attributes_for :comments


end

app/models/comment.rb
class Comment < ActiveRecord::Base
  belongs_to :advert
end

app/controllers/adverts_controller.rb
class AdvertsController < ApplicationController
  before_action :authenticate_admin! , only: [:new ,:edit, :update, :destroy]
  before_action :set_advert, only: [:show, :edit, :update, :destroy]

  def active
    @adverts = Advert.active.paginate(:page => params[:page], :per_page => 5)
    render  :index
  end
  def inactive
    @adverts = Advert.inactive.paginate(:page => params[:page], :per_page => 5)
    render  :index
  end
  def job_hunt
    @adverts = Advert.job_hunt.paginate(:page => params[:page], :per_page => 5)
    render  :index
  end
  def buy
    @adverts = Advert.buy.paginate(:page => params[:page], :per_page => 5)
    render  :index
  end
  def sell
    @adverts = Advert.sell.paginate(:page => params[:page], :per_page => 5)
    render  :index
  end
  def hire
    @adverts = Advert.hire.paginate(:page => params[:page], :per_page => 5)
    render  :index
  end
  def exchange
    @adverts = Advert.exchange.paginate(:page => params[:page], :per_page => 5)
    render  :index
  end


  # GET /adverts
  # GET /adverts.json
  def index
    @adverts = Advert.paginate(:page => params[:page], :per_page => 5)
  end

  # GET /adverts/1
  # GET /adverts/1.json
  def show

    @advert = Advert.find(params[:id])
 
    respond_to do |format|
      format.html
      format.pdf do
        pdf = ReportPdf.new(@advert)
        send_data pdf.render, filename: 'report.pdf', type: 'application/pdf'

      end

    end
  end

  # GET /adverts/new
  def new
    @advert = Advert.new
  end

  # GET /adverts/1/edit
  def edit
  end

  # POST /adverts
  # POST /adverts.json
  def create
    @advert = current_admin.adverts.create(advert_params)

    respond_to do |format|
      if @advert.save
        format.html { redirect_to @advert, notice: 'Advert was successfully created.' }
        format.json { render :show, status: :created, location: @advert }
      else
        format.html { render :new }
        format.json { render json: @advert.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /adverts/1
  # PATCH/PUT /adverts/1.json
  def update
    respond_to do |format|
      if @advert.update(advert_params)
        format.html { redirect_to @advert, notice: 'Advert was successfully updated.' }
        format.json { render :show, status: :ok, location: @advert }
      else
        format.html { render :edit }
        format.json { render json: @advert.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /adverts/1
  # DELETE /adverts/1.json
  def destroy
    @advert.destroy
    respond_to do |format|
      format.html { redirect_to adverts_url, notice: 'Advert was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
  # Use callbacks to share common setup or constraints between actions.
  def set_advert
    @advert = Advert.find(params[:id])
  end

  # Never trust parameters from the scary internet, only allow the white list through.
  def advert_params
    params.require(:advert).permit(:job_hunt, :hire, :buy, :sell, :exchange, :title, :description, :name, :surname, :email, :mobile, :date, :active, :address, :image, :image1, :image2, :image3,   comments_attributes: [:name,:content,:advert_id,:_destroy])
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  before_action :authenticate_admin! , only: [:show,:new ,:edit, :update, :destroy]
  before_action :set_comment, only: [:show, :edit, :update, :destroy]
  # GET /comments
  # GET /comments.json
  def index
    @comments = Comment.all
  end

  # GET /comments/1
  # GET /comments/1.json
  def show
  end

  # GET /comments/new
  def new
    @comment = Comment.new
  end

  # GET /comments/1/edit
  def edit
  end

  # POST /comments
  # POST /comments.json
  def create
    @comment = Comment.new(comment_params)

    respond_to do |format|
      if @comment.save
        format.html { redirect_to advert_path(@comment.advert_id), notice: 'Comment was successfully created.' }
        format.json { render :show, status: :created, location: @comment }
      else
        format.html { render :new }
        format.json { render json: @comment.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /comments/1
  # PATCH/PUT /comments/1.json
  def update
    respond_to do |format|
      if @comment.update(comment_params)
        format.html { redirect_to @comment, notice: 'Comment was successfully updated.' }
        format.json { render :show, status: :ok, location: @comment }
      else
        format.html { render :edit }
        format.json { render json: @comment.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /comments/1
  # DELETE /comments/1.json
  def destroy
    @comment.destroy
    respond_to do |format|
      format.html { redirect_to comments_url, notice: 'Comment was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_comment
      @comment = Comment.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def comment_params
      params.require(:comment).permit(:content, :advert_id, :name)
    end
end

app/helpers/adverts_helper.rb
module AdvertsHelper
	def is_my_advert?(advert)
		if current_admin && advert.admin_id == current_admin.id 
			return true
		else
			return false
		end	
	end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/views/adverts/_form.html.erb
<%= form_for @advert, :html => { :class => 'form-horizontal' } do |f| %>
  <div class="control-group">
    <%= f.label :title, :class => 'control-label' %>
    <div class="controls">
      <%= f.text_field :title, :class => 'text_field' %>
    </div>
  </div>
  <div class="control-group">
    <%= f.label :description, :class => 'control-label' %>
    <div class="controls">
      <%= f.text_area :description, :class => 'text_area' %>
    </div>
        <br> Let us know if this AD is active</br>
    <br></br>
    <div class="control-group">
      <%= f.label :active, :class => 'control-label' %>

      <div class="controls">
        <%= f.check_box :active, :class => 'check_box' %>
      </div>
    </div>
    <br></br>
    <ul>
    <div class="control-group", "controls"> Category, please choose: 
    <br></br>
    <li>Looking for a Job?<br><%= f.check_box :job_hunt, :class => 'check_box' %></br></li>
    <br></br>
    <li>Looking for Employees ?
    <br><%= f.check_box :hire, :class => 'check_box' %></br></li>
    <br></br>
    <li>Looking to Buy ?
    <br><%= f.check_box :buy, :class => 'check_box' %></br></li>
    <br></br>
    <li>Looking to Sell ? 
    <br><%= f.check_box :sell, :class => 'check_box' %></br></li>
    <br></br>
    <li>Looking to Exchange/Swap ? 
    <br><%= f.check_box :exchange, :class => 'check_box' %></br></li>
    </ul></br>
    <br></br>
    </div>
    <div class="control-group">
      <%= f.label :image, :class => 'control-label' %>
      <div class="controls">
        <%= f.file_field :image, :class => 'text_field' %>
        <%= f.file_field :image1, :class => 'text_field' %>
        <%= f.file_field :image2, :class => 'text_field' %>
        <%= f.file_field :image3, :class => 'text_field' %>
      </div>
    </div>
    <div class="control-group">
      <%= f.label :name, :class => 'control-label' %>
      <div class="controls">
        <%= f.text_field :name, :class => 'text_field' %>
      </div>
    </div>
    <div class="control-group">
      <%= f.label :surname, :class => 'control-label' %>
      <div class="controls">
        <%= f.text_field :surname, :class => 'text_field' %>
      </div>
    </div>
    <div class="control-group">
      <%= f.label :address, :class => 'control-label' %>
      <div class="controls">
        <%= f.text_field :address, :class => 'text_field' %>
      </div>
    </div>
    <div class="control-group">
      <%= f.label :email, :class => 'control-label' %>
      <div class="controls">
        <%= f.text_field :email, :class => 'text_field' %>
      </div>
    </div>
    <div class="control-group">
      <%= f.label :mobile, :class => 'control-label' %>
      <div class="controls">
        <%= f.text_field :mobile, :class => 'text_field' %>
      </div>
    </div>


        <br><%= image_tag "http://maps.google.com/maps/api/staticmap?size=1900x1000&sensor=true&zoom=14&markers=#{@advert.latitude},#{@advert.longitude}" %></br>
  <div class="form-actions">
    <%= f.submit nil, :class => 'btn btn-primary' %>
    <%= link_to t('.cancel', :default => t("helpers.links.cancel")),
                adverts_path, :class => 'btn btn-info' %>
  </div>
<% end %>

app/views/adverts/edit.html.erb
<%- model_class = Advert -%>
<div class="page-header">
  <h1><%=t '.title', :default => [:'helpers.titles.edit', 'Edit %{model}'], :model => model_class.model_name.human.titleize %></h1>
</div>
<%= render :partial => 'form' %>

app/views/adverts/index.html.erb
<%- model_class = Advert -%>
<div class="page-header">
  <h1><%=t '.title', :default => model_class.model_name.human.pluralize.titleize %></h1>
</div>
<table class="table table-striped supertable">
  <p><%= link_to t('.new', :default => t("helpers.links.new")),
            new_advert_path,
            :class => ['btn btn-large' , "icon-cogs"] %></p><br />
  <thead>
      <tr>
      <th><%= model_class.human_attribute_name(:title) %></th>
      <th><%= model_class.human_attribute_name(:description) %></th>
      <th><%= model_class.human_attribute_name(:active) %></th>
      <th><%= model_class.human_attribute_name(:name) %></th>
      <th><%= model_class.human_attribute_name(:surname) %></th>
      <th><%= model_class.human_attribute_name(:address) %></th>
      <th><%= model_class.human_attribute_name(:email) %></th>
      <th><%= model_class.human_attribute_name(:mobile) %></th>
      <th><%= model_class.human_attribute_name(:created_at) %></th>
      <th><%=t '.actions', :default => t("helpers.actions") %></th>
      <th>Options:</th>
    </tr>
    </thead>
  <tbody>
    <% @adverts.each do |advert| %>
      <tr class="supertr" ,"container-fluid">
        
        <td><%= advert.title %></td>
        <td><%= advert.description %></td>
        <td><%= advert.active %></td>
        <td><%= advert.name %></td>
        <td><%= advert.surname %></td>
        <td><%= advert.address %></td>
        <td><%= advert.email %></td>
        <td><%= advert.mobile %></td>
  
                <td><%=l advert.created_at %></td>
        <td><%= image_tag "http://maps.google.com/maps/api/staticmap?size=300x300&sensor=true&zoom=14&markers=#{advert.latitude},#{advert.longitude}" %></td>
        <td><br><%= link_to("Show",advert, method: 'get', :class => ["btn btn-info btn-mini"]) %></br>
        <br><%= link_to("PDF",advert_path(advert, format: :pdf), method: 'get', :class => ["btn btn btn-mini"]) %></br>
        <% if is_my_advert?(advert) %>

        <br><%= link_to t('.edit', :default => t("helpers.links.edit")),
                      edit_advert_path(advert), :class => ['btn btn-success btn-mini'] %></br>
        <br><%= link_to t('.destroy', :default => t("helpers.links.destroy")),
                      advert_path(advert),
                      :method => :delete,
                      :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) },
                      :class => ['btn btn-mini btn-danger'] %></br></td>
     
        </td>
        <% end %>
            
      </tr>
    
    <% end %>
  </tbody>
</table>
<div class="digg_pagination">
    <div class="page_info">
      <%= page_entries_info @adverts %>
    </div>
    <%= will_paginate @adverts, :container => false %>
  </div>

app/views/adverts/new.html.erb
<%- model_class = Advert -%>
<div class="page-header">
  <h1><%=t '.title', :default => [:'helpers.titles.new', 'New %{model}'], :model => model_class.model_name.human.titleize %></h1>
</div>
<%= render :partial => 'form' %>

app/views/adverts/show.html.erb
<%- model_class = Advert -%>
<div class="page-header">
  <h1><%=t '.title', :default => model_class.model_name.human.titleize %></h1>
</div>

<dl class="dl-horizontal">
  <dt><strong><%= model_class.human_attribute_name(:title) %>:</strong></dt>
  <dd><%= @advert.title %></dd>
  <dt><strong><%= model_class.human_attribute_name(:description) %>:</strong></dt>
  <dd><%= @advert.description %></dd>
    <dt><strong><%= model_class.human_attribute_name(:active) %>:</strong></dt>
  <dd><%= @advert.active %></dd>

 <div><br><dt><strong><%= model_class.human_attribute_name(:image) %>:</strong></dt></br>
 <br><%= image_tag @advert.image.url(:medium) %></br>
 <br><%= link_to 'Original Image' , @advert.image.url %></br></div>

 <div><br><dt><strong><%= model_class.human_attribute_name(:image1) %>:</strong></dt></br>
 <br><%= image_tag @advert.image1.url(:medium) %></br>
 <br><%= link_to 'Original Image' , @advert.image1.url %></br></div>

 <div><br><dt><strong><%= model_class.human_attribute_name(:image2) %>:</strong></dt></br>
 <br><%= image_tag @advert.image2.url(:medium) %></br>
 <br><%= link_to 'Original Image' , @advert.image2.url %></br></div>
 <div><br><dt><strong><%= model_class.human_attribute_name(:image3) %>:</strong></dt></br>
 <br><%= image_tag @advert.image3.url(:medium) %></br>
 <br><%= link_to 'Original Image' , @advert.image3.url %></br></div>
  <br><dt><strong><%= model_class.human_attribute_name(:job_hunt) %>:</strong></dt>
  <dd><%= @advert.job_hunt %></dd>
 <dt><strong><%= model_class.human_attribute_name(:hire) %>:</strong></dt>
  <dd><%= @advert.hire %></dd>
 <dt><strong><%= model_class.human_attribute_name(:buy) %>:</strong></dt>
  <dd><%= @advert.buy %></dd>
 <dt><strong><%= model_class.human_attribute_name(:sell) %>:</strong></dt>
  <dd><%= @advert.sell %></dd>
 <dt><strong><%= model_class.human_attribute_name(:exchange) %>:</strong></dt>
  <dd><%= @advert.exchange %></dd>
  <dt><strong><%= model_class.human_attribute_name(:name) %>:</strong></dt>
  <dd><%= @advert.name %></dd>
  <dt><strong><%= model_class.human_attribute_name(:surname) %>:</strong></dt>
  <dd><%= @advert.surname %></dd>
    <dt><strong><%= model_class.human_attribute_name(:address) %>:</strong></dt>
  <dd><%= @advert.address %></dd>
  <dt><strong><%= model_class.human_attribute_name(:email) %>:</strong></dt>
  <dd><%= @advert.email %></dd>
  <dt><strong><%= model_class.human_attribute_name(:mobile) %>:</strong></dt>
  <dd><%= @advert.mobile %></dd>

   <dt><strong><%= model_class.human_attribute_name(:comment) %>:</strong></dt>
  <dd><% @advert.comments.each do |comment| %>
 <%= comment.content %> (<%= comment.name %>)<br />
<% end %>
  </dd>
</dl>
<%= render partial: 'comments/form', locals: {comment: Comment.new(advert_id: @advert.id)} %>
<%= image_tag "http://maps.google.com/maps/api/staticmap?size=1900x1000&sensor=true&zoom=14&markers=#{@advert.latitude},#{@advert.longitude}" %>
<div class="form-actions">
  <%= link_to t('.back', :default => t("helpers.links.back")),
              adverts_path, :class => 'btn btn-info'  %>
  <%= link_to("PDF",advert_path(@advert,format: :pdf), method: 'get', :class => ["btn btn btn"]) %>
     <% if is_my_advert?(@advert) %>
  <%= link_to t('.edit', :default => t("helpers.links.edit")),
              edit_advert_path(@advert), :class => 'btn btn-success' %>
  <%= link_to t('.destroy', :default => t("helpers.links.destroy")),
              advert_path(@advert),
              :method => 'delete',
              :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) },
              :class => 'btn btn-danger' %>

              <% end %>
</div> 

app/views/comments/_form.html.erb
<%= form_for(comment) do |f| %>
  <% if comment.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@comment.errors.count, "error") %> prohibited this comment from being saved:</h2>

      <ul>
      <% comment.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>
  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :content %><br>
    <%= f.text_area :content %>
  </div>
  <div class="field">
    <%= f.hidden_field :advert_id %>
  </div>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/layouts/application.html.erb
 <!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=Edge,chrome=1">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title><%= content_for?(:title) ? yield(:title) : "Adverter" %></title>
    <%= csrf_meta_tags %>

    <!-- Le HTML5 shim, for IE6-8 support of HTML elements -->
    <!--[if lt IE 9]>
      <script src="//cdnjs.cloudflare.com/ajax/libs/html5shiv/3.6.1/html5shiv.js" type="text/javascript"></script>
    <![endif]-->

    <%= stylesheet_link_tag "application", :media => "all" %>

    <!-- For third-generation iPad with high-resolution Retina display: -->
    <!-- Size should be 144 x 144 pixels -->
    <%= favicon_link_tag 'apple-touch-icon-144x144-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png', :sizes => '144x144' %>

    <!-- For iPhone with high-resolution Retina display: -->
    <!-- Size should be 114 x 114 pixels -->
    <%= favicon_link_tag 'apple-touch-icon-114x114-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png', :sizes => '114x114' %>

    <!-- For first- and second-generation iPad: -->
    <!-- Size should be 72 x 72 pixels -->
    <%= favicon_link_tag 'apple-touch-icon-72x72-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png', :sizes => '72x72' %>

    <!-- For non-Retina iPhone, iPod Touch, and Android 2.1+ devices: -->
    <!-- Size should be 57 x 57 pixels -->
    <%= favicon_link_tag 'apple-touch-icon-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png' %>

    <!-- For all other devices -->
    <!-- Size should be 32 x 32 pixels -->
    <%= favicon_link_tag 'favicon.ico', :rel => 'shortcut icon' %>

    <%= javascript_include_tag "application" %>
  </head>
  <body>

    <div class="navbar navbar ">
      <div class="navbar-inner">
        <div class="container-fluid best_gradient">
          <a class="btn btn-navbar" data-target=".nav-collapse" data-toggle="collapse">
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
                      </a>
          <a  href="/" class="btn btn-large"> Adverter <i class="icon-barcode"> </i></a>
          <div class="container-fluid nav-collapse">
                      <ul class="nav">

            <% if admin_signed_in? %>
                            <li><%= link_to("Edit Account",edit_admin_registration_path, method: 'get', :class => ["btn btn-info btn","icon-rocket"]) %></li>
              <li><%= link_to("Log Out",destroy_admin_session_path, method: 'delete', :class => ["btn btn-info btn","icon-off"]) %></li>
            <% else %>
        <li><%= link_to("Forgot Password?",new_admin_password_path, method: 'get', :class => ["btn btn-info btn","icon-rocket"]) %></li>
              <li><%= link_to("Sign in",new_admin_session_path, method: 'get', :class => ["btn btn-info btn","icon-rocket"]) %></li>
              <li><%= link_to("Sign Up",new_admin_registration_path, method: 'get', :class => ["btn btn-info btn","icon-rocket"]) %></li>
            <% end %>
  <div class="btn-group"></div>
  <div class="btn-group","container-fluid nav-collapse">
  <a href="/adverts/active"  type="button" class="btn btn-default">Active Adverts</a>
  <a href="/adverts/inactive" type="button" class="btn btn-default">Inactive Adverts</a><br>
  <div class="btn-group"><button type="button" class="btn btn-default dropdown-toggle" data-toggle="dropdown">
      Choose Advert Category:
    <span class="caret"></span>
    </button>
  <ul class="dropdown-menu" role="menu">
    <li><a href="/adverts/job_hunt">Job Hunt</a></li>
    <li><a href="/adverts/hire">Hire</a></li>
    <li><a href="/adverts/buy">Buy</a></li>
    <li><a href="/adverts/sell">Sell</a></li>
    <li><a href="/adverts/exchange">Exchange</a></li>
    </ul></div>
  </div>
</div>
</div>
        </div>
      </div>
    </div>

<link href="//netdna.bootstrapcdn.com/font-awesome/4.0.3/css/font-awesome.css" rel="stylesheet">
    <div class="container-fluid">
      <div class="row-fluid">
            <ul class="nav nav-list">

              <a
   class="btn btn-facebook"
   href="http://www.facebook.com/sharer.php?u=_URL_"
>
   <i class="fa fa-facebook"></i>   Share 
</a>
 <a
   class="btn btn-twitter"
   href="http://twitter.com/share?url=_URL_&text=Posted an Advert on this page!&via=TWITTER_NAME"
>
   <i class="fa fa-twitter"></i>  Share</a>
<a
   class="btn btn-linkedin"
   href="http://www.linkedin.com/shareArticle?url=_URL_"
>
   <i class="fa fa-linkedin"> Share</i>
</a>
<br>

          <div class="span9">
          <%= bootstrap_flash %>
          <%= yield %>
        </div>
      </div><!--/row-->



      <footer>
      <p><a  href="/admins/moderate" class="btn btn-large"> grfx 2k14</a></p>
      </footer>
    </div> <!-- /container -->
  </body>
</html>